name: CI

on: [push, pull_request]

jobs:
  
  build_updates_only:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Clean up files
        run: |
           rm _ark/songs/updates/update_song_catcher.dta
           rm _ark/songs/updates/vanilla_songs_lut.dta
           rm _ark/songs/missing_song_data.dta
           rm _ark/songs/missing_song_data_updates.dta
           rm  -rf _ark/songs/dta_sections
           mv _ark/songs/beencaughtstealing _ark/songs/updates/beencaughtstealing
           mv _ark/songs/getupstandup _ark/songs/updates/getupstandup
           mv _ark/songs/nooneknows _ark/songs/updates/nooneknows
           mv _ark/songs/radarlove _ark/songs/updates/radarlove
           mv _ark/songs/thepoweroflove _ark/songs/updates/thepoweroflove
           mv _ark/songs/updates _ark/songs/songs_updates
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Songs-Updates
          path: _ark/songs
