name: CI

on: [push, pull_request]

jobs:
  build_xbox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build ARK
        run: |
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
          dependencies/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 5
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Xbox
          path: _build/xbox

  build_ps3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build ARK
        run: |
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
          dependencies/arkhelper dir2ark ./_ark ./_build/ps3/USRDIR/gen -n "patch_ps3" -e -v 5
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-PS3
          path: _build/ps3

  build_xbox_keys:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build ARK
        run: |
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
          pip install gitpython
          python python_scripts/enable_keys.py
          dependencies/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 5
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Xbox-additional-keys
          path: _build/xbox

  build_ps3_keys:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build ARK
        run: |
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
          pip install gitpython
          python python_scripts/enable_keys.py
          dependencies/arkhelper dir2ark ./_ark ./_build/ps3/USRDIR/gen -n "patch_ps3" -e -v 5
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-PS3-additional-keys
          path: _build/ps3

  build_xbox_pad_is_guitar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build ARK
        run: |
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
          sed -i -e "s/(hx_xbox kControllerVocals)/(hx_xbox kControllerGuitar)/" _ark/config/joypad.dta
          sed -i -e "s/(digital kControllerVocals)/(digital kControllerGuitar)/" _ark/config/joypad.dta
          sed -i -e "s/(analog kControllerVocals)/(analog kControllerGuitar)/" _ark/config/joypad.dta
          sed -i -e "s/(dualshock kControllerVocals)/(dualshock kControllerGuitar)/" _ark/config/joypad.dta
          perl -pi -e 's/\n/\r\n/' _ark/config/joypad.dta
          dependencies/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 5
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Xbox-pad-is-guitar
          path: _build/xbox

  build_ps3_pad_is_guitar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build ARK
        run: |
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
          sed -i -e "s/(hx_xbox kControllerVocals)/(hx_xbox kControllerGuitar)/" _ark/config/joypad.dta
          sed -i -e "s/(digital kControllerVocals)/(digital kControllerGuitar)/" _ark/config/joypad.dta
          sed -i -e "s/(analog kControllerVocals)/(analog kControllerGuitar)/" _ark/config/joypad.dta
          sed -i -e "s/(dualshock kControllerVocals)/(dualshock kControllerGuitar)/" _ark/config/joypad.dta
          perl -pi -e 's/\n/\r\n/' _ark/config/joypad.dta
          dependencies/arkhelper dir2ark ./_ark ./_build/ps3/USRDIR/gen -n "patch_ps3" -e -v 5
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-PS3-pad-is-guitar
          path: _build/ps3
