name: CI

on: [push, pull_request]

jobs:
  
  build_updates_only:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Remove PS3 files
        run: |
          find . -name "*.*_ps3" -type f -delete
          find . -name "*.*_wii" -type f -delete
      - name: Clean up files
        run: |
           rm _ark/songs/missing_song_data.dta
           rm _ark/songs/missing_song_data_updates.dta
           rm  -rf _ark/songs/dta_sections
           rm  -rf _ark/songs/dta_collection
           mv _ark/songs/beencaughtstealing _ark/songs/updates/beencaughtstealing
           mv _ark/songs/getupstandup _ark/songs/updates/getupstandup
           mv _ark/songs/nooneknows _ark/songs/updates/nooneknows
           mv _ark/songs/radarlove _ark/songs/updates/radarlove
           mv _ark/songs/thepoweroflove _ark/songs/updates/thepoweroflove
           mv _ark/songs/updates _ark/songs/songs_updates
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-YARG-Updates
          path: _ark/songs

  build_wii_main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Download Mackiloha
        run: |
          pip install requests
          python dependencies/dev_scripts/download_mackiloha.py
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod +x dependencies/linux/arkhelper
          chmod +x dependencies/linux/dtab
          chmod +x dependencies/linux/superfreq
          pip install gitpython
          pip install mido
      - name: Revert mid updates to their originals
        run: |
          rm -rf _ark/songs/
      - name: Remove PS3 files
        run: |
          find . -name "*.*_ps3" -type f -delete
          find . -name "*.*_xbox" -type f -delete
      - name: Print build info
        run: |
          echo $GITHUB_SHA_SHORT
          python dependencies/dev_scripts/add_devbuild.py $GITHUB_SHA_SHORT
      - name: Build ARK
        run: |
          dependencies/linux/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 6
      - name: Extract ARK
        run: |
          dependencies/linux/arkhelper ark2dir ./_build/xbox/gen/patch_xbox.hdr ./rb3/rb3 -a
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Wii-rawfiles
          path: rb3

  build_xbox_standard:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Download Mackiloha
        run: |
          pip install requests
          python dependencies/dev_scripts/download_mackiloha.py
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod +x dependencies/linux/arkhelper
          chmod +x dependencies/linux/dtab
          chmod +x dependencies/linux/superfreq
          pip install gitpython
          pip install mido
      - name: Remove PS3 files
        run: |
          find . -name "*.*_ps3" -type f -delete
      - name: Print build info
        run: |
          echo $GITHUB_SHA_SHORT
          python dependencies/dev_scripts/add_devbuild.py $GITHUB_SHA_SHORT
      - name: Build ARK
        run: |
          dependencies/linux/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 6
      - name: Remove Excess files
        run: |
          find . -name "*.txt" -type f -delete
          find . -name "*.zbm" -type f -delete
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Xbox
          path: _build/xbox

  build_xbox_keys:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Download Mackiloha
        run: |
          pip install requests
          python dependencies/dev_scripts/download_mackiloha.py
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod +x dependencies/linux/arkhelper
          chmod +x dependencies/linux/dtab
          chmod +x dependencies/linux/superfreq
          pip install gitpython
          pip install mido
      - name: Remove PS3 files
        run: |
          find . -name "*.*_ps3" -type f -delete
      - name: Add Moggs
        run: |
          python dependencies/dev_scripts/add_moggs.py
      - name: Print build info
        run: |
          echo $GITHUB_SHA_SHORT
          python dependencies/dev_scripts/add_devbuild.py $GITHUB_SHA_SHORT
      - name: Build ARK
        run: |
          dependencies/linux/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 6
      - name: Remove Excess files
        run: |
          find . -name "*.txt" -type f -delete
          find . -name "*.zbm" -type f -delete
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Xbox-Keys-Moggs
          path: _build/xbox

  build_xbox_no_mid_updates:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Download Mackiloha
        run: |
          pip install requests
          python dependencies/dev_scripts/download_mackiloha.py
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod +x dependencies/linux/arkhelper
          chmod +x dependencies/linux/dtab
          chmod +x dependencies/linux/superfreq
          pip install gitpython
          pip install mido
      - name: Revert mid updates to their originals
        run: |
          rm -rf _ark/songs/
      - name: Remove PS3 files
        run: |
          find . -name "*.*_ps3" -type f -delete
          find . -name "*.*_wii" -type f -delete
      - name: Print build info
        run: |
          echo $GITHUB_SHA_SHORT
          python dependencies/dev_scripts/add_devbuild.py $GITHUB_SHA_SHORT
      - name: Build ARK
        run: |
          dependencies/linux/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 6
      - name: Remove Excess files
        run: |
          find . -name "*.txt" -type f -delete
          find . -name "*.zbm" -type f -delete
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Xbox-Vanilla-Song-Data
          path: _build/xbox

  build_ps3_standard:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Download Mackiloha
        run: |
          pip install requests
          python dependencies/dev_scripts/download_mackiloha.py
      - name: Set env
        run: |
          pip install gitpython
          pip install mido
          pip install requests
      - name: fetch TrueAncestor PKG Repacker
        run: |
          python dependencies/dev_scripts/download_ta_pkg_repacker.py
      - name: Remove Xbox files
        run: |
          Get-ChildItem _ark/ -recurse -include *.*_xbox | remove-item
          Get-ChildItem _ark/ -recurse -include *.*_wii | remove-item
      - name: Print build info
        run: |
          $GITHUB_SHA_SHORT="$(git rev-parse --short HEAD)".ToUpper()
          python dependencies/dev_scripts/add_devbuild.py $GITHUB_SHA_SHORT
      - name: Build ARK
        run: |
          dependencies/windows/arkhelper.exe dir2ark _ark _build/ps3/USRDIR/gen -n "patch_ps3" -e -v 6
      - name: Build PKG
        run: |
          $sha_short="$(git rev-parse --short HEAD)".ToUpper()
          $content="UP8802-BLUS30463_00-RB3DXNITE"
          $packageversion="1.05"
          dependencies/ta_pkg_repacker_tools/make_package_npdrm_retail.exe --k-licensee 0x00000000000000000000000000000000 --drm-type Local --package-version $packageversion --content-type GameData --content-id ($content + $sha_short) dependencies/ta_pkg_repacker_tools/package.conf _build/ps3

      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: RB3DX-PS3
          path: '*.pkg'

  build_ps3_keys:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Download Mackiloha
        run: |
          pip install requests
          python dependencies/dev_scripts/download_mackiloha.py
      - name: Set env
        run: |
          pip install gitpython
          pip install mido
          pip install requests
      - name: fetch TrueAncestor PKG Repacker
        run: |
          python dependencies/dev_scripts/download_ta_pkg_repacker.py
      - name: Remove Xbox files
        run: |
          Get-ChildItem _ark/ -recurse -include *.*_xbox | remove-item
          Get-ChildItem _ark/ -recurse -include *.*_wii | remove-item
      - name: Add Moggs
        run: |
          python dependencies/dev_scripts/add_moggs.py
      - name: Print build info
        run: |
          $GITHUB_SHA_SHORT="$(git rev-parse --short HEAD)".ToUpper()
          python dependencies/dev_scripts/add_devbuild.py $GITHUB_SHA_SHORT
      - name: Build ARK
        run: |
          dependencies/windows/arkhelper.exe dir2ark _ark _build/ps3/USRDIR/gen -n "patch_ps3" -e -v 6
      - name: Build PKG
        run: |
          $sha_short="$(git rev-parse --short HEAD)".ToUpper()
          $content="UP8802-BLUS30463_00-RB3DXNITE"
          $packageversion="1.05"
          dependencies/ta_pkg_repacker_tools/make_package_npdrm_retail.exe --k-licensee 0x00000000000000000000000000000000 --drm-type Local --package-version $packageversion --content-type GameData --content-id ($content + $sha_short) dependencies/ta_pkg_repacker_tools/package.conf _build/ps3

      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: RB3DX-PS3-Keys-Moggs
          path: '*.pkg'