name: CI

on: [push, pull_request]

jobs:
  
  build_yarg_updates:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Remove PS3 files
        run: |
          find . -name "*.*_ps3" -type f -delete
          find . -name "*.*_wii" -type f -delete
      - name: Clean up files
        run: |
           rm _ark/songs/missing_song_data.dta
           rm _ark/songs/missing_song_data_updates.dta
           rm  -rf _ark/songs/dta_sections
           rm  -rf _ark/songs/dta_collection
           mv _ark/songs/beencaughtstealing _ark/songs/updates/beencaughtstealing
           mv _ark/songs/getupstandup _ark/songs/updates/getupstandup
           mv _ark/songs/nooneknows _ark/songs/updates/nooneknows
           mv _ark/songs/radarlove _ark/songs/updates/radarlove
           mv _ark/songs/thepoweroflove _ark/songs/updates/thepoweroflove
           mv _ark/songs/updates _ark/songs/songs_updates
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-YARG-Updates
          path: _ark/songs

  build_xbox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Print build info
        run: |
          echo $GITHUB_SHA_SHORT
          python dependencies/dev_scripts/add_devbuild.py $GITHUB_SHA_SHORT
      - name: Build ARK
        run: |
          dependencies/python/configure_build.py xbox
          dependencies/linux/ninja

      - name: Remove Excess files
        run: |
          find . -name "*.txt" -type f -delete
          find . -name "*.zbm" -type f -delete
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Xbox
          path: out/xbox

  build_ps3:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Print build info
        run: |
          $GITHUB_SHA_SHORT="$(git rev-parse --short HEAD)".ToUpper()
          python dependencies/dev_scripts/add_devbuild.py $GITHUB_SHA_SHORT
      - name: Build ARK
        run: |
          python dependencies/python/configure_build.py ps3
          dependencies/windows/ninja.exe
      - name: Build PKG
        run: |
          $sha_short="$(git rev-parse --short HEAD)".ToUpper()
          $content="UP8802-BLUS30463_00-RB3DXNITE"
          $packageversion="1.05"
          dependencies/ta_pkg_repacker_tools/make_package_npdrm_retail.exe --k-licensee 0x00000000000000000000000000000000 --drm-type Local --package-version $packageversion --content-type GameData --content-id ($content + $sha_short) dependencies/ta_pkg_repacker_tools/package.conf out/ps3

      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-PS3
          path: '*.pkg'