name: CI

on: [push, pull_request]

jobs:
  build_yarg:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Build Files
        run: |
          sed -i '1d' _ark/dx/song_updates/songs_updates.dta
          dependencies/python/configure_build.py yarg
          dependencies/linux/ninja

      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-YARG-Updates
          path: out/yarg

  build_xbox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Pull commit hash for locale
        run: |
          python dependencies/dev_scripts/add_devbuild.py
      - name: Build ARK
        run: |
          dependencies/python/configure_build.py xbox
          dependencies/linux/ninja

      - name: Remove Excess files
        run: |
          find . -name "*.txt" -type f -delete
          find . -name "*.zbm" -type f -delete
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Xbox
          path: out/xbox

  build_ps3:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Pull commit hash for locale
        run: |
          $GITHUB_SHA_SHORT="$(git rev-parse --short HEAD)".ToUpper()
          python dependencies/dev_scripts/add_devbuild.py
      - name: Build ARK
        run: |
          python dependencies/python/configure_build.py ps3
          dependencies/windows/ninja.exe
      - name: Build PKG
        run: |
          $sha_short="$(git rev-parse --short HEAD)".ToUpper()
          $content="UP8802-BLUS30463_00-RB3DXNITE"
          $packageversion="1.05"
          dependencies/ta_pkg_repacker_tools/make_package_npdrm_retail.exe --k-licensee 0x00000000000000000000000000000000 --drm-type Local --package-version $packageversion --content-type GameData --content-id ($content + $sha_short) dependencies/ta_pkg_repacker_tools/package.conf out/ps3

      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-PS3
          path: '*.pkg'