name: CI

on: [push, pull_request]

jobs:
  build_xbox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Set env
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
      - name: Build ARK
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
          pip install gitpython
          pip install mido
          python dependencies/give_3dx_pro_strings.py
          find . -name "*.*_ps3" -type f -delete
          echo $GITHUB_SHA_SHORT
          sed -i -e "s/devbuild/"$GITHUB_SHA_SHORT"/g" _ark/ui/locale/*/locale_updates_keep.dta
          dependencies/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 6
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Base-Xbox
          path: _build/xbox

  build_ps3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Set env
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
      - name: Build ARK
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
          pip install gitpython
          pip install mido
          python dependencies/give_3dx_pro_strings.py
          find . -name "*.*_xbox" -type f -delete
          echo $GITHUB_SHA_SHORT
          sed -i -e "s/devbuild/"$GITHUB_SHA_SHORT"/g" _ark/ui/locale/*/locale_updates_keep.dta
          dependencies/arkhelper dir2ark ./_ark ./_build/ps3/USRDIR/gen -n "patch_ps3" -e -v 6
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Base-PS3
          path: _build/ps3

  build_xbox_keys:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Set env
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
      - name: Build ARK
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
          pip install gitpython
          pip install mido
          python dependencies/give_3dx_pro_strings.py
          python dependencies/enable_keys.py
          find . -name "*.*_ps3" -type f -delete
          echo $GITHUB_SHA_SHORT
          sed -i -e "s/devbuild/"$GITHUB_SHA_SHORT"/g" _ark/ui/locale/*/locale_updates_keep.dta
          dependencies/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 6
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Xbox-additional-keys
          path: _build/xbox

  build_ps3_keys:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Set env
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
      - name: Build ARK
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
          find . -name "*.*_xbox" -type f -delete
          pip install gitpython
          pip install mido
          python dependencies/give_3dx_pro_strings.py
          python dependencies/enable_keys.py
          echo $GITHUB_SHA_SHORT
          sed -i -e "s/devbuild/"$GITHUB_SHA_SHORT"/g" _ark/ui/locale/*/locale_updates_keep.dta
          dependencies/arkhelper dir2ark ./_ark ./_build/ps3/USRDIR/gen -n "patch_ps3" -e -v 6
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-PS3-additional-keys
          path: _build/ps3

  build_xbox_animation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Set env
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
      - name: Build ARK
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
          pip install gitpython
          pip install mido
          python dependencies/give_3dx_pro_strings.py
          python dependencies/enable_animation.py
          find . -name "*.*_ps3" -type f -delete
          echo $GITHUB_SHA_SHORT
          sed -i -e "s/devbuild/"$GITHUB_SHA_SHORT"/g" _ark/ui/locale/*/locale_updates_keep.dta
          dependencies/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 6
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Xbox-Animated-Textures
          path: _build/xbox

  build_ps3_animation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Set env
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
      - name: Build ARK
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
          find . -name "*.*_xbox" -type f -delete
          pip install gitpython
          pip install mido
          python dependencies/give_3dx_pro_strings.py
          python dependencies/enable_animation.py
          echo $GITHUB_SHA_SHORT
          sed -i -e "s/devbuild/"$GITHUB_SHA_SHORT"/g" _ark/ui/locale/*/locale_updates_keep.dta
          dependencies/arkhelper dir2ark ./_ark ./_build/ps3/USRDIR/gen -n "patch_ps3" -e -v 6
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-PS3-Animated-Textures
          path: _build/ps3

  build_xbox_animation_keys:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Set env
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
      - name: Build ARK
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
          pip install gitpython
          pip install mido
          python dependencies/give_3dx_pro_strings.py
          python dependencies/enable_animation.py
          python dependencies/enable_keys.py
          find . -name "*.*_ps3" -type f -delete
          echo $GITHUB_SHA_SHORT
          sed -i -e "s/devbuild/"$GITHUB_SHA_SHORT"/g" _ark/ui/locale/*/locale_updates_keep.dta
          dependencies/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 6
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Xbox-Animated-Textures-and-Keys
          path: _build/xbox

  build_ps3_animation_keys:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Set env
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
      - name: Build ARK
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
          find . -name "*.*_xbox" -type f -delete
          pip install gitpython
          pip install mido
          python dependencies/give_3dx_pro_strings.py
          python dependencies/enable_animation.py
          python dependencies/enable_keys.py
          echo $GITHUB_SHA_SHORT
          sed -i -e "s/devbuild/"$GITHUB_SHA_SHORT"/g" _ark/ui/locale/*/locale_updates_keep.dta
          dependencies/arkhelper dir2ark ./_ark ./_build/ps3/USRDIR/gen -n "patch_ps3" -e -v 6
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-PS3-Animated-Textures-and-Keys
          path: _build/ps3

  build_xbox_pad_is_guitar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set env
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
      - name: Build ARK
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
          find . -name "*.*_ps3" -type f -delete
          sed -i -e "s/;#define FORCE_PAD/#define FORCE_PAD/" _ark/config/macros.dta
          echo $GITHUB_SHA_SHORT
          sed -i -e "s/devbuild/"$GITHUB_SHA_SHORT"/g" _ark/ui/locale/*/locale_updates_keep.dta
          dependencies/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 6
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Xbox-pad-is-guitar
          path: _build/xbox

  build_ps3_pad_is_guitar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set env
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
      - name: Build ARK
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
          find . -name "*.*_xbox" -type f -delete
          sed -i -e "s/;#define FORCE_PAD/#define FORCE_PAD/" _ark/config/macros.dta
          echo $GITHUB_SHA_SHORT
          sed -i -e "s/devbuild/"$GITHUB_SHA_SHORT"/g" _ark/ui/locale/*/locale_updates_keep.dta
          dependencies/arkhelper dir2ark ./_ark ./_build/ps3/USRDIR/gen -n "patch_ps3" -e -v 6
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-PS3-pad-is-guitar
          path: _build/ps3

  build_ps3_stock_inst_mapping:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set env
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
      - name: Build ARK
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
          find . -name "*.*_xbox" -type f -delete
          sed -i -e "s/;#define STOCK_PAD/#define STOCK_PAD/" _ark/config/macros.dta
          echo $GITHUB_SHA_SHORT
          sed -i -e "s/devbuild/"$GITHUB_SHA_SHORT"/g" _ark/ui/locale/*/locale_updates_keep.dta
          dependencies/arkhelper dir2ark ./_ark ./_build/ps3/USRDIR/gen -n "patch_ps3" -e -v 6

      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-PS3-stock-instrument-mapping
          path: _build/ps3
