name: CI

on: [push, pull_request]

jobs:
  build_xbox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build ARK
        run: |
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
          dependencies/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 6
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Base-Xbox
          path: _build/xbox

  build_ps3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build ARK
        run: |
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
          dependencies/arkhelper dir2ark ./_ark ./_build/ps3/USRDIR/gen -n "patch_ps3" -e -v 6
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Base-PS3
          path: _build/ps3

  build_xbox_keys:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build ARK
        run: |
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
          pip install gitpython
          python dependencies/enable_keys.py
          dependencies/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 6
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Xbox-additional-keys
          path: _build/xbox

  build_ps3_keys:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build ARK
        run: |
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
          pip install gitpython
          python dependencies/enable_keys.py
          dependencies/arkhelper dir2ark ./_ark ./_build/ps3/USRDIR/gen -n "patch_ps3" -e -v 6
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-PS3-additional-keys
          path: _build/ps3

  build_xbox_pad_is_guitar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build ARK
        run: |
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
          sed -i -e "s/(hx_xbox kControllerVocals)/(hx_xbox kControllerGuitar)/" _ark/config/joypad.dta
          sed -i -e "s/(digital kControllerVocals)/(digital kControllerGuitar)/" _ark/config/joypad.dta
          sed -i -e "s/(analog kControllerVocals)/(analog kControllerGuitar)/" _ark/config/joypad.dta
          sed -i -e "s/(dualshock kControllerVocals)/(dualshock kControllerGuitar)/" _ark/config/joypad.dta
          dependencies/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 6
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Xbox-pad-is-guitar
          path: _build/xbox

  build_ps3_pad_is_guitar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build ARK
        run: |
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
          sed -i -e "s/(hx_xbox kControllerVocals)/(hx_xbox kControllerGuitar)/" _ark/config/joypad.dta
          sed -i -e "s/(digital kControllerVocals)/(digital kControllerGuitar)/" _ark/config/joypad.dta
          sed -i -e "s/(analog kControllerVocals)/(analog kControllerGuitar)/" _ark/config/joypad.dta
          sed -i -e "s/(dualshock kControllerVocals)/(dualshock kControllerGuitar)/" _ark/config/joypad.dta
          dependencies/arkhelper dir2ark ./_ark ./_build/ps3/USRDIR/gen -n "patch_ps3" -e -v 6
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-PS3-pad-is-guitar
          path: _build/ps3

  build_ps3_author_controller_faking:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build ARK
        run: |
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
          sed -i -e "s/(ro_drums_ps3_ghwt kControllerDrum)/(ro_drums_ps3_ghwt kControllerRealGuitar)/" _ark/config/joypad.dta
          sed -i -e "s/(konami_drums_ps3_rr kControllerDrum)/(konami_drums_ps3_rr kControllerKeys)/" _ark/config/joypad.dta
          dependencies/arkhelper dir2ark ./_ark ./_build/ps3/USRDIR/gen -n "patch_ps3" -e -v 6

      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-PS3-author-controller-faking
          path: _build/ps3

      - name: version
          run: echo "::set-output name=version::$(_build/ps3 --version)"
          id: version

      - name: release
          uses: actions/create-release@v1
          id: create_release
          with:
            draft: false
            prerelease: false
            release_name: ${{ steps.version.outputs.version }}
            tag_name: ${{ github.ref }}
            body_path: CHANGELOG.md
          env:
            GITHUB_TOKEN: ${{ github.token }}

      - name: upload artifact
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ github.token }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: _build/ps3/RB3DX-PS3-author-controller-faking.zip
            asset_name: RB3DX-PS3-author-controller-faking
            asset_content_type: application/zip