name: CI

on: [push, pull_request]

jobs:
  build_xbox_vanilla_mids:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
      - name: Restore vanilla mids
        run: |
          find _ark/songs/updates/ -name "*.mid" -type f -delete
          find _ark/songs/updates/ -empty -type d -delete
          sed -i -e "s/;#define VANILLA_MIDS/#define VANILLA_MIDS/" _ark/config/macros.dta
      - name: Remove PS3 files
        run: |
          find . -name "*.*_ps3" -type f -delete
      - name: Print build info
        run: |
          echo $GITHUB_SHA_SHORT
          sed -i -e "s/devbuild/"$GITHUB_SHA_SHORT"/g" _ark/ui/locale/*/locale_updates_keep.dta
      - name: Build ARK
        run: |
          dependencies/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 6
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Base-Xbox-vanilla_mids
          path: _build/xbox

  build_xbox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
          pip install gitpython
          pip install mido
      - name: Embed pro string upgrades
        run: |
          python dependencies/give_3dx_pro_strings.py
      - name: Remove PS3 files
        run: |
          find . -name "*.*_ps3" -type f -delete
      - name: Print build info
        run: |
          echo $GITHUB_SHA_SHORT
          sed -i -e "s/devbuild/"$GITHUB_SHA_SHORT"/g" _ark/ui/locale/*/locale_updates_keep.dta
      - name: Build ARK
        run: |
          dependencies/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 6
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Base-Xbox
          path: _build/xbox

  build_xbox_keys:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
          pip install gitpython
          pip install mido
      - name: Embed pro string/key upgrades
        run: |
          python dependencies/give_3dx_pro_strings.py
          python dependencies/enable_keys.py
      - name: Remove PS3 files
        run: |
          find . -name "*.*_ps3" -type f -delete
      - name: Print build info
        run: |
          echo $GITHUB_SHA_SHORT
          sed -i -e "s/devbuild/"$GITHUB_SHA_SHORT"/g" _ark/ui/locale/*/locale_updates_keep.dta
      - name: Build ARK
        run: |
          dependencies/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 6
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Xbox-additional-keys
          path: _build/xbox

  build_ps3_vanilla_mids:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
      - name: Restore vanilla mids
        run: |
          find _ark/songs/updates/ -name "*.mid" -type f -delete
          find _ark/songs/updates/ -empty -type d -delete
          sed -i -e "s/;#define VANILLA_MIDS/#define VANILLA_MIDS/" _ark/config/macros.dta
      - name: Remove Xbox files
        run: |
          find . -name "*.*_xbox" -type f -delete
      - name: Print build info
        run: |
          echo $GITHUB_SHA_SHORT
          sed -i -e "s/devbuild/"$GITHUB_SHA_SHORT"/g" _ark/ui/locale/*/locale_updates_keep.dta
      - name: Build ARK
        run: |
          dependencies/arkhelper dir2ark ./_ark ./_build/ps3/gen -n "patch_ps3" -e -v 6
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Base-PS3-vanilla_mids
          path: _build/ps3

  build_ps3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
          pip install gitpython
          pip install mido
      - name: Embed pro string upgrades
        run: |
          python dependencies/give_3dx_pro_strings.py
      - name: Remove Xbox files
        run: |
          find . -name "*.*_xbox" -type f -delete
      - name: Print build info
        run: |
          echo $GITHUB_SHA_SHORT
          sed -i -e "s/devbuild/"$GITHUB_SHA_SHORT"/g" _ark/ui/locale/*/locale_updates_keep.dta
      - name: Build ARK
        run: |
          dependencies/arkhelper dir2ark ./_ark ./_build/ps3/USRDIR/gen -n "patch_ps3" -e -v 6
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Base-PS3
          path: _build/ps3

  build_ps3_keys:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
          pip install mido
          pip install gitpython
      - name: Remove Xbox files
        run: |
          find . -name "*.*_xbox" -type f -delete
      - name: Embed pro string/key upgrades
        run: |
          python dependencies/give_3dx_pro_strings.py
          python dependencies/enable_keys.py
      - name: Print build info
        run: |
          echo $GITHUB_SHA_SHORT
          sed -i -e "s/devbuild/"$GITHUB_SHA_SHORT"/g" _ark/ui/locale/*/locale_updates_keep.dta
      - name: Build ARK
        run: |
          dependencies/arkhelper dir2ark ./_ark ./_build/ps3/USRDIR/gen -n "patch_ps3" -e -v 6
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-PS3-additional-keys
          path: _build/ps3

  build_ps3_stock_inst_mapping:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
          pip install mido
          pip install gitpython
      - name: Remove Xbox files
        run: |
          find . -name "*.*_xbox" -type f -delete
      - name: Embed pro string upgrades
        run: |
          python dependencies/give_3dx_pro_strings.py
      - name: Restore stock instrument mapping
        run: |
          sed -i -e "s/;#define STOCK_PAD/#define STOCK_PAD/" _ark/config/macros.dta
      - name: Print build info
        run: |
          echo $GITHUB_SHA_SHORT
          sed -i -e "s/devbuild/"$GITHUB_SHA_SHORT"/g" _ark/ui/locale/*/locale_updates_keep.dta
      - name: Build ARK
        run: |
          dependencies/arkhelper dir2ark ./_ark ./_build/ps3/USRDIR/gen -n "patch_ps3" -e -v 6

      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-PS3-stock-instrument-mapping
          path: _build/ps3
